### ISSUE TITLE
suspicious casing found in Felis Catus Hispanicus or http://hesperomys.com/n/41333

### ISSUE THREAD

**Issue by jhpoelen** [JelleZijlstra/taxonomy#3]
Hi!

As I was working on https://github.com/globalbioticinteractions/nomer/issues/144, I stumbled across original name with suspicious casing:

Felis Catus Hispanicus
http://hesperomys.com/n/41333

I was expecting something like:

Felis catus hispanicus

where only the first word (genus) is capitalized. 

Can you help me understand why I found the unexpected casing?

![image](https://user-images.githubusercontent.com/1084872/214691907-1b032622-f8a7-4fb4-9fd9-c41d532e344b.png)

**Comment by JelleZijlstra** [comment]
The original_name field is meant to be the original name as it was spelled in the original, with weird caps, hyphens, diacritics, and all. There is a separate "corrected_original_name" field (called "Cleaned original name" on the website) that normalizes capitalization, diacritics, etc.

The file I sent you has original_name, not corrected_original_name. I imagine corrected_original_name is more useful for most use cases, so I'll change the exporter to use that field.

**Comment by JelleZijlstra** [comment]
Also, if you want a truly weird original name, http://hesperomys.com/n/72704 is a better example :)

**Comment by jhpoelen** [comment]
@JelleZijlstra great that you are keeping the verbatim (or originalName). 

And yes, ```Caprinae gen. indet. (aff. Capricornis) roylei``` from http://hesperomys.com/n/72704 definitely looks funny. 

Thanks for clarifying. 

PS. Would it be fair to assume that the Felis Catus Hispanicus casing comes from either an OCR error (machine transcription error) or typo (human transcription error). Or are there other reasons that you've encountered?

**Comment by JelleZijlstra** [comment]
There may be mistakes, but "Felis Catus Hispanicus" is actually correct: https://www.biodiversitylibrary.org/item/53898#page/576/mode/1up. "Hispanicus" is capitalized in the original, and so is "Catus" (on p. 518).

**Comment by jhpoelen** [comment]
Nice! Great to be able to go straight to the source document (or at least a digital copy) 

Erxleben, J.C.P. 1777. [Systema regni animalis per classes, ordines, genera, species, varietates cum synonymia et historia animalium. Classis I. Mammalia](http://hesperomys.com/a/36060). Impensis Weygandianis, Leipzig, 636 pp.

![image](https://user-images.githubusercontent.com/1084872/214711402-2874076d-7fee-4a5e-bd0d-8b6bd56426eb.png)

**Comment by JelleZijlstra** [comment]
Closing as the question has been answered, feel free to open a new issue if you have any additional questions or feedback.

**Comment by jhpoelen** [comment]
@JelleZijlstra thanks for taking the time to respond to my observation. Also, I appreciate that you keep the verbatim names around!
